## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
len(application_df['SPECIAL_CONSIDERATIONS'].unique())

2

In [3]:
len(application_df[application_df['SPECIAL_CONSIDERATIONS']!='N'])

27

In [3]:
name_counts = application_df['NAME'].value_counts()
name_counts

NAME
PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: count, Length: 19568, dtype: int64

In [4]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=['EIN'], inplace = True)
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value_application = 275
application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts().loc[lambda x: x < cutoff_value_application].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x: x>1 ]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value_name = 20
name_to_replace = application_df['NAME'].value_counts().loc[lambda x: x < cutoff_value_name].index

# Replace in dataframe
for cls in name_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(cls,'UNK')

# Check to make sure replacement was successful
application_df['NAME'].value_counts()

NAME
UNK                                               22409
PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
                                                  ...
AMERICAN IRIS SOCIETY                                21
ARIZONA FEDERATION OF GARDEN CLUBS                   21
GENERAL FEDERATION OF WOMENS CLUBS ARIZONA INC       20
DISABLED AMERICAN VETERANS AUXILIARY INC             20
TEXAS MASTER GARDENER ASSOCIATION INC                20
Name: count, Length: 122, dtype: int64

In [13]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value_classificaton = 1882
classifications_to_replace = application_df['CLASSIFICATION'].value_counts().loc[lambda x: x < cutoff_value_classificaton].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [14]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_dummies = pd.get_dummies(application_df)
application_df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_ALPHA PHI SIGMA INC,NAME_ALTRUSA INTERNATIONAL FOUNDATION INC,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [15]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies['IS_SUCCESSFUL'].values
X = application_df_dummies.drop('IS_SUCCESSFUL', axis =1 ).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                13280

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 15741 (61.49 KB)
Trainable params: 15741 (61.49 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 3ms/step - loss: 0.4840 - accuracy: 0.7617
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4611 - accuracy: 0.7745
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4573 - accuracy: 0.7779
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4552 - accuracy: 0.7794
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4533 - accuracy: 0.7804
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4524 - accuracy: 0.7801
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4508 - accuracy: 0.7813
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4499 - accuracy: 0.7819
Epoch 9/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4487 - accuracy: 0.7829
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4481 - accuracy: 0.7816
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4477 - accuracy: 0.7839
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4474 - accuracy: 0.7837
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4456 - accuracy: 0.7847
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4462 - accuracy: 0.7845
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4458 - accuracy: 0.7830
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4451 - accuracy: 0.7837
Epoch 17/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4449 - accuracy: 0.7850
Epoch 18/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4441 - accuracy: 0.7856
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4435 - accuracy: 0.7862
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4435 - accuracy: 0.7848
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4430 - accuracy: 0.7848
Epoch 22/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4423 - accuracy: 0.7860
Epoch 23/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4428 - accuracy: 0.7855
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4425 - accuracy: 0.7859
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4419 - accuracy: 0.7866
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4413 - accuracy: 0.7870
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4413 - accuracy: 0.7868
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4403 - accuracy: 0.7863
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4406 - accuracy: 0.7866
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4402 - accuracy: 0.7856
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4402 - accuracy: 0.7874
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4398 - accuracy: 0.7865
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4396 - accuracy: 0.7864
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4395 - accuracy: 0.7874
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4395 - accuracy: 0.7862
Epoch 36/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4392 - accuracy: 0.7869
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4388 - accuracy: 0.7873
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4389 - accuracy: 0.7873
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4385 - accuracy: 0.7884
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4387 - accuracy: 0.7877
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4384 - accuracy: 0.7875
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4385 - accuracy: 0.7872
Epoch 43/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4380 - accuracy: 0.7882
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4377 - accuracy: 0.7874
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4377 - accuracy: 0.7873
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4371 - accuracy: 0.7874
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4375 - accuracy: 0.7885
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4373 - accuracy: 0.7881
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4373 - accuracy: 0.7881
Epoch 50/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4369 - accuracy: 0.7888
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4368 - accuracy: 0.7889
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4362 - accuracy: 0.7883
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4364 - accuracy: 0.7895
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4360 - accuracy: 0.7891
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4364 - accuracy: 0.7903
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4358 - accuracy: 0.7893
Epoch 57/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4356 - accuracy: 0.7890
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4357 - accuracy: 0.7897
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4357 - accuracy: 0.7890
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4354 - accuracy: 0.7893
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4353 - accuracy: 0.7896
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4355 - accuracy: 0.7895
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4353 - accuracy: 0.7889
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4350 - accuracy: 0.7901
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4346 - accuracy: 0.7895
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4352 - accuracy: 0.7898
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4348 - accuracy: 0.7901
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4346 - accuracy: 0.7898
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4345 - accuracy: 0.7901
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4343 - accuracy: 0.7896
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4346 - accuracy: 0.7892
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4344 - accuracy: 0.7894
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4340 - accuracy: 0.7905
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4339 - accuracy: 0.7895
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4337 - accuracy: 0.7907
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4336 - accuracy: 0.7900
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4340 - accuracy: 0.7904
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4337 - accuracy: 0.7901
Epoch 79/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4338 - accuracy: 0.7899
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4339 - accuracy: 0.7904
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4331 - accuracy: 0.7909
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4333 - accuracy: 0.7905
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4332 - accuracy: 0.7904
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4333 - accuracy: 0.7905
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4336 - accuracy: 0.7894
Epoch 86/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4330 - accuracy: 0.7909
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4333 - accuracy: 0.7900
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4330 - accuracy: 0.7909
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4329 - accuracy: 0.7910
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4329 - accuracy: 0.7908
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4326 - accuracy: 0.7901
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4329 - accuracy: 0.7910
Epoch 93/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4327 - accuracy: 0.7905
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4324 - accuracy: 0.7913
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4328 - accuracy: 0.7904
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4322 - accuracy: 0.7908
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4324 - accuracy: 0.7910
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4324 - accuracy: 0.7895
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4326 - accuracy: 0.7907
Epoch 100/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4324 - accuracy: 0.7907

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4899 - accuracy: 0.7694 - 530ms/epoch - 2ms/step
Loss: 0.4899435043334961, Accuracy: 0.769446074962616

In [ ]:
# Export our model to HDF5 file
# filepath = "\AlphabetSoupCharity.h5"
# nn.save(filepath,save_format='h5')